import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

// import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { ProductListComponent } from '@src/app/product-list/product-list.component';
import { ProductDetailsComponent } from '@src/app/product-details/product-details.component';
import { CartComponent } from '@src/app/cart/cart.component';

export const routes: Routes = [
  // { path: '', redirectTo: '/', pathMatch: 'full' },
  { path: '', component: ProductListComponent },
  // { path: 'products', component: ProductListComponent },
  { path: 'products/:productId', component: ProductDetailsComponent },
  { path: 'cart', component: CartComponent },
  // { path: 'shipping', component: ShippingComponent },
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
